name: PyPI Publish

on: push

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install build
        run: python -m pip install build
      - name: Clean
        run: rm -rf dist build *.egg-info
      - name: Build for distribution
        # remove bdist_wheel for pip installation with compiling cuda extensions
        run: python -m build --sdist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
